### ISSUE TITLE
Extension is not working on Linux

### ISSUE THREAD

**Issue by pjox** [hampustagerud/atom-remember-session#2]
Steps to reproduce:

Open a file or folder.
Open a few tabs.
Close Atom.
Open Atom again.

What I expect:

The editor to reload and show the open tabs from previous session, with my last activated tab on front.

What happens:

No tabs are opened.

**Comment by mekkanizer** [comment]
Here's a stack trace, if it can help anyhow:
TypeError: undefined is not a function
    at attachListeners (/home/mekkanizer/.atom/packages/remember-session/lib/remember-session.coffee:28:5)
    at Object.module.exports.activate (/home/mekkanizer/.atom/packages/remember-session/lib/remember-session.coffee:8:7)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:240:19)
    at /opt/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:452:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:431:19)
